version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://ahmedmukarram6:mukarram69@cluster0.rpdb5nm.mongodb.net/booksapp?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=muka55am
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo-data: