apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: book-review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mukarram1/book-review-app-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://ahmedmukarram6:mukarram69@cluster0.rpdb5nm.mongodb.net/booksapp?retryWrites=true&w=majority&appName=Cluster0"
        - name: JWT_SECRET
          value: "muka55am"
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
