name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      shell: bash
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/book-review-app-backend:latest ./backend

    - name: Build frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/book-review-app-frontend:latest ./frontend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push backend Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/book-review-app-backend:latest

    - name: Push frontend Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/book-review-app-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/mongo-deployment.yaml
        kubectl apply -f kubernetes/mongo-service.yaml
        kubectl apply -f kubernetes/backend-deployment.yaml
        kubectl apply -f kubernetes/backend-service.yaml
        kubectl apply -f kubernetes/frontend-deployment.yaml
        kubectl apply -f kubernetes/frontend-service.yaml

    - name: Show all resources in namespace
      run: kubectl get all -n book-review
