name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker to use Minikube's environment
        run: |
          Write-Host "Configuring Docker to use Minikube's daemon..."
          & minikube docker-env | Invoke-Expression

      - name: Build backend Docker image
        run: |
          Write-Host "Building backend image from .\book-review-app\backend"
          docker build --tag "mukarram1/book-review-app-backend:latest" --file ".\book-review-app\backend\Dockerfile" ".\book-review-app\backend"

      - name: Build frontend Docker image
        run: |
          Write-Host "Building frontend image from .\book-review-app\frontend"
          docker build --tag "mukarram1/book-review-app-frontend:latest" --file ".\book-review-app\frontend\Dockerfile" ".\book-review-app\frontend"

      - name: Login to Docker Hub
        run: echo "dckr_pat_QqATUKpMvUs0PKglBs0lTeHcPKQ" | docker login -u "mukarram1" --password-stdin

      - name: Push backend Docker image
        run: docker push mukarram1/book-review-app-backend:latest

      - name: Push frontend Docker image
        run: docker push mukarram1/book-review-app-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/mongo-deployment.yaml
          kubectl apply -f kubernetes/mongo-service.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml

      - name: Show all resources in namespace
        run: kubectl get all -n book-review
